projectName: Identity and Access Management Concepts
jsonFilePath: ./input.json
baseUrl: https://hiteshkumawat.com
portalHeading: Identity and Access Management Concepts
portalDescription: >-
  A product designer / developer who design and develop experiences that make
  people's lives easy.
portalTitle: Hitesh Kumawat - Product Designer who codes
searchPlaceholder: Search...
useAlphabetsCategory: true
homeLink: https://hiteshkumawat.com/
logoLink: https://hiteshkumawat.com/
ctaText: Get Started
aboutLink: https://hiteshkumawat.com/about
productsLink: https://hiteshkumawat.com/work
logoImgUrl: https://hiteshkumawat.com/favicon.ico
ctaLink: https://hiteshkumawat.com/about
copyrightText: Hitesh Kumawat - © 2023
faviconUrl: https://hiteshkumawat.com/favicon.ico
googleTagManagerId: G-6GL9BERWJ0
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
templateRoot:
  - ./templates
  - ./templates
homeTemplatePath: ./templates/homePageTemplate.ejs
categoryTemplatePath: ./templates/categoryTemplate.ejs
pageTemplatePath: ./templates/pagesTemplate.ejs
outputDir: ./output
socialLinks:
  - platform: Twitter
    url: https://twitter.com/hiteshkrkumawat
  - platform: Github
    url: https://github.com/Hiteshkumawat
  - platform: Blog
    url: https://compile7.org/decompile/author/hitesh-kumawat/
  - platform: Email
    url: mailto:hiteshkumawat19@gmail.com
theme:
  primaryColor: '#333333'
  secondaryColor: '#ffffff'
  backgroundColor: '#f5f5f5'
  textColor: '#000000'
  accentColor: '#007bff'
fonts:
  - family: Inter
    weights:
      - 400
      - 500
      - 600
  - family: Urbanist
    weights:
      - 500
      - 600
      - 700
